### ISSUE TITLE
Allow modifying / disabling repos in /etc

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-pkgng#105]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.19.1
- Ruby: 2.6
- Distribution: FreeBSD 12.2-RELEASE
- Module version: 2.4.0

## How to reproduce (e.g Puppet code you use)

according to the README,

> Disabling the FreeBSD default repository is done with:
>
> ```puppet
> pkgng::repo { 'FreeBSD':
>  enabled => false,
> }
> ``` 

## What are you seeing

This, however, just adds a file in `/usr/local/etc/pkg/repos`, but that does not seem to actually disable the repo

## What behaviour did you expect instead

I would expect to disable the FreeBSD repo, by modifying `/etc/pkg/FreeBSD.conf`

## Any additional information you'd like to impart

I don't know if this is a bug in pkg.

**Comment by brooksdavis** [comment]
Is `false` a synonym for `no` in libucl? I've noticed that libucl is to accepting of nonsense (e.g. misspelling `enabled` and `enable` results is silently doing nothing).

**Comment by igalic** [comment]
debugged this with the help of @RhodiumToad on IRC:

```irc
22:09 <RhToad> what does  pkg stats   output?
22:09 <RhToad> specifically for  Number of repositories:
22:10 <RhToad> I just put a copy of that FreeBSD.conf onto one of my VMs and it has correctly disabled access to the freebsd repo
```

Turns out the number was, indeed 1.
The `pkg: leatherman: duplicate dependency listing: curl` (among many other packages) were resolved with `pkg upgrade -f`;
